modstitch.platform=moddevgradle

deps.minecraft=26.3
deps.pack_format=97
deps.neoforge=26.3.0.1-beta
deps.mcRange=26.3
deps.minecraftRange=[26.3,26.4)
deps.kotlinForForge=thedarkcolour:kotlinforforge-neoforge:6.3.0+26.3.dropconfirm.1
deps.changelogKotlin=Kotlin for Forge (NeoForge) `v6.3.0` or newer.
